env:
  global:
    - CC_TEST_REPORTER_ID=27df0a8ad648d4af0f931c1b0101cca2278fcfd755112b4d563650c45f48071c
language: ruby
dist: focal
os: linux
rvm:
  - 3.1.2
  - 3.0.4
  - 2.7.6
cache: bundler
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script: bundle exec rake
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
addons:
  apt:
    packages:
      - libimage-exiftool-perl
